MODEL:
  WEIGHTS: ''    # 中间模型,可以不设置，训练代码自动寻找最新保存的模型 qss, 如果设置，则使用该模型
compute_precision:
  grad_scaler: true
  teacher:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    hash_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
  student:
    backbone:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    dino_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
    hash_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp16
        buffer_dtype: fp32
    ibot_head:
      sharding_strategy: SHARD_GRAD_OP
      mixed_precision:
        param_dtype: fp16
        reduce_dtype: fp32
        buffer_dtype: fp32
dino:
  loss_weight: 1.0
  head_n_prototypes: 65536  # qss
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.0
hash: # qss
  do_or_not: True
  hash_bit: 64
  loss_hash_reg: 0.01

ibot:
  loss_weight: 1.0  # qss
  mask_sample_probability: 0.5
  mask_ratio_min_max:
  - 0.1
  - 0.6  # qss
  separate_head: true
  head_n_prototypes: 65536  # qss
  head_bottleneck_dim: 256
  head_nlayers: 3
  head_hidden_dim: 2048
train:
  batch_size_per_gpu: 64
  data_path: /home/datasets/AID  #/home/datasets/UCMerced_LandUse/Images # qss
  train_ratio: 0.5 # qss 0.5 for AID dataset, 0.8 for UCMD dataset
  output_dir: .
  saveckp_freq: 20
  seed: 0
  num_workers: 8
  OFFICIAL_EPOCH_LENGTH: 80  # qss, 80 for AID dataset, 30 for UCMD dataset
  cache_dataset: true
  centering: "centering" # or "sinkhorn_knopp"
student:
  arch: vit_small  # qss
  patch_size: 14  # qss
  drop_path_rate: 0.05 # official 0.3
  layerscale: 1.0e-5 #1.0e-2, qss
  drop_path_uniform: true
  pretrained_weights: '/dinov2_models/dinov2_vits14_pretrain.pth' # qss, 预训练模型
  ffn_layer: "mlp"
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 0
  interpolate_antialias: false
  interpolate_offset: 0.1
teacher:
  momentum_teacher: 0.992
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 30  # qss
optim:
  epochs: 100  # qss
  weight_decay: 0.04
  weight_decay_end: 0.4
  base_lr: 0.001 # qss, 2e-4, 0.004, learning rate for a batch size of 1024 = 0.004
  lr: 0.  # will be set after applying scaling rule
  warmup_epochs: 10  # qss
  min_lr: 1.0e-06
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.2
  layerwise_decay: 0.9
  adamw_beta1: 0.9
  adamw_beta2: 0.999
crops:
  global_crops_scale:
  - 0.6  # qss
  - 1.0
  local_crops_number: 8
  local_crops_scale:
  - 0.05  # qss
  - 0.5  # qss
  global_crops_size: 224  # qss, 518
  local_crops_size: 98 # qss
evaluation:
  eval_period_iterations: 80

